### ISSUE TITLE
tabulate_shared_TCR_chains call to assert

### ISSUE THREAD

**Issue by Scott1009** [mjdufort/TCRtools#1]
tabulate_shared_TCR_chains uses a naked call to assert.  At first it was picking up gtools:assert() in my particular case, but that function is defunct.  Adding library(checkmate) to my configuration fixed that, but perhaps tabulate_shared_TCR_chains() should use the fully qualified call checkmate:assert().

Thanks!

**Comment by mjdufort** [comment]
Fixed by modifying to checkmate::assert().  Also verified that all other usage of checkmate functions specifies the package, and added package checkmate as a dependency.
